# Generated by Django 4.2.4 on 2023-09-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_delete_client_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('aadhar', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client_data')),
            ],
        ),
    ]
